### ISSUE TITLE
Episodes in English

### ISSUE THREAD

**Issue by nopoh41** [robsdedude/southpark-downloader#3]
Hello,

Thanks for bringing this little tool. This is more of a feature request. Even on southpark.de it's possible to watch the episodes in English.

Could you maybe integrate an option to get English episodes instead of German? You wrote that it probably is just a short change in get_seasons.sh. I couldn't find out what the URL for the English episodes look like. Maybe you could take a look into that?

Thanks.

**Comment by robsdedude** [comment]
This is currently not possible. The language selection works via a cookie but setting `youtube-dl --add-header "Cookie: SPS_video_language=en"` does not do the trick.

https://github.com/ytdl-org/youtube-dl/issues/21271

**Comment by robsdedude** [comment]
I'll close this for now.

**Comment by rmolina** [comment]
Hi, I was able to download episodes in English and in Spanish by changing the URLs in the script:

For English: 
`url='https://southpark.cc.com/feeds/carousel/video/6154fc40-b7a3-4387-94cc-fc42fc47376e/30/1/json/!airdate/season-'${1}`

For Spanish: 
`url='https://southpark.cc.com/feeds/carousel/video/351c1323-0b96-402d-a8b9-40d01b2e9bde/30/1/json/!airdate/temporada-'${1}'?lang=es'`
