### ISSUE TITLE
Please update your script with English and Spanish support

### ISSUE THREAD

**Issue by CHJ85** [robsdedude/southpark-downloader#4]
Hi there. Could you update this script with English and Spanish support?

English:
url='https://southpark.cc.com/feeds/carousel/video/6154fc40-b7a3-4387-94cc-fc42fc47376e/30/1/json/!airdate/season-'${1}

Spanish:
url='https://southpark.cc.com/feeds/carousel/video/351c1323-0b96-402d-a8b9-40d01b2e9bde/30/1/json/!airdate/temporada-'${1}'?lang=es'

**Comment by robsdedude** [comment]
Thanks for opening a new issue. I completely forgot about @rmolina 's [comment](https://github.com/robsdedude/southpark-downloader/issues/3#issuecomment-592254110).  Right now I'm fiddling around with these URLs but the seem to work for me too, so far.
